version: '3'

#------------------------
#******* DEC Core *******
#------------------------
services:
  decwas:
    container_name: decwas
    image: ibmcom/websphere-traditional:latest
    ports:
      - "9080:9080"
      - "9043:9043"
    environment:
      - LICENSE=accept
      - PROFILE_NAME=AppSrv01
      - CELL_NAME=DefaultCell01
    volumes:
      - ./artifacts:/home/was/artifact
      - ./scripts:/home/was/scripts
      #- was_data:/opt/IBM/WebSphere
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8888:8080


  #******* Infraestructura *******
  #...............................
  #> Servidor de colas MQ
  mqserver:
    # admin:passw0rd
    container_name: mqserver
    image: ibmcom/mq:latest
    ports:
      - "1414:1414"
      - "9443:9443"
    environment:
      - LICENSE=accept
      - MQ_QMGR_NAME=QM1
      - MQSNOAUT=yes
      - MQ_DEV=true

  #> Servidor de base de datos Oracle
  ora:
    image: gvenzl/oracle-xe:21-slim
    container_name: ora
    environment:
      ORACLE_ALLOW_REMOTE: 'true'
      ORACLE_ENABLE_XDB: 'true'
      ORACLE_DISABLE_ASYNCH_IO: 'true'
      ORACLE_USER: 'system'
      ORACLE_PASSWORD: 'oracle'
    ports:
      - 1521:1521
      - 5500:5500
    volumes:
      - oracle_data:/opt/oracle/oradata/XE

volumes:
  oracle_data:
    driver: local
  was_data:
    driver: local